### ISSUE TITLE
Doesn't seem to work with the latest Xcode 6.3

### ISSUE THREAD

**Issue by FWFabio** [dropbox/XCoverage#3]
Toggling Cmd+shift+\ does nothing on Xcode. I've tried with the sample app

**Comment by wangshengjia** [comment]
I have same issue with Xcode 6.3

**Comment by FWFabio** [comment]
Xcode 6.3.2 doesn't load the plugin even after updating the info.plist file

**Comment by mozeryansky** [comment]
Same issue. Console shows:
5/26/15 9:19:55.768 AM Xcode[99954]: [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XCoverage.xcplugin' not present in DVTPlugInCompatibilityUUIDs

**Comment by mozeryansky** [comment]
I fixed the problem and created a pull request. My forked version will work on Xcode 6.3.2.
It is a Xcode 6.3 issue with the order of loading plugins.

The Dash plugin had a similar problem, which they fixed by waiting for the application to finish launching:
https://github.com/omz/Dash-Plugin-for-Xcode/commit/3014f12c4e91a6be3a0521600f65879acae05b0a

**Comment by tylermann** [comment]
Thanks for looking into this! Added a couple minor comments to the PR and we can hopefully get it in soon.

**Comment by tylermann** [comment]
Should be fixed in the latest commit thanks to @mozeryansky . Let us know if you still see any issues on the tip of master.
